import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {execFileSync} from 'node:child_process';
import {createStore,emptyState} from '../server/store.mjs';import {clipControls,clipEnvelope,clipStyle} from '../server/clip-effects.mjs';import {COMPOSITIONS} from '../server/motion-catalog.mjs';import {correlateEnvelopes} from '../server/audio-sync.mjs';import {mixerFilters,mixerSettings} from '../server/audio-mixer.mjs';import {FFMPEG,runProcess} from '../server/media.mjs';import {exportProject} from '../exporters/index.mjs';
async function fixture(){const dataDir=await fs.mkdtemp(path.join(os.tmpdir(),'cutton-pro-')),s=emptyState();s.width=s.height=160;s.fps=25;s.assets=[{id:'asset_source',name:'source.mp4',kind:'video',duration:40,videoDuration:40,audioDuration:40,hasAudio:true,path:path.join(dataDir,'source.mp4'),sceneId:null}];await fs.writeFile(path.join(dataDir,'state.json'),JSON.stringify(s));return {store:await createStore({dataDir}),dataDir};}
async function add(store,start,duration=3,sourceIn=5,track='video',lane=0){return (await store.execute('timeline.add',{assetId:'asset_source',start,duration,in:sourceIn,track,lane})).result;}
test('roll/slide/slip/ripple preserve expected outer edit points, reject insufficient handles atomically',async()=>{const {store}=await fixture(),a=await add(store,0),b=await add(store,3),c=await add(store,6);await add(store,0,9,0,'audio');
 await store.execute('timeline.trim',{id:b.id,mode:'roll',edge:'in',frames:10});let s=store.getState();assert.equal(s.clips[0].duration,3.4);assert.equal(s.clips[1].start,3.4);assert.equal(s.clips[1].in,5.4);assert.equal(s.clips[1].duration,2.6);assert.equal(s.clips[2].start,6);
 await store.execute('edit.undo');await store.execute('timeline.trim',{id:b.id,mode:'slide',frames:5});s=store.getState();assert.equal(s.clips[1].duration,3);assert.equal(s.clips[1].start,3.2);assert.equal(s.clips[2].in,5.2);assert.equal(s.clips[2].start+s.clips[2].duration,9);
 await store.execute('edit.undo');await store.execute('timeline.trim',{id:b.id,mode:'slip',frames:-25});assert.equal(store.getState().clips[1].in,4);await store.execute('edit.undo');
 await store.execute('timeline.trim',{id:b.id,mode:'ripple',edge:'in',frames:25});s=store.getState();assert.equal(s.clips[1].start,3);assert.equal(s.clips[1].duration,2);assert.equal(s.clips[2].start,5);assert.equal(s.clips[3].duration,9);await store.execute('edit.undo');
 const before=store.getState();await assert.rejects(store.execute('timeline.trim',{id:b.id,mode:'roll',frames:10000}));assert.deepEqual(store.getState(),before);await assert.rejects(store.execute('timeline.trim',{id:a.id,mode:'slide',frames:1}));
});
test('insert splits both tracks, shifts annotations and undo restores everything',async()=>{const {store}=await fixture();await add(store,0,8,2);await add(store,0,8,2,'audio');await store.execute('caption.add',{text:'字幕',start:5,duration:1});await store.execute('graphics.compose',{preset:'lower',title:'タイトル',start:0,duration:8});await store.execute('marker.add',{time:5});const before=store.getState();
 await store.execute('timeline.place',{assetId:'asset_source',mode:'insert',track:'video',start:3,in:10,duration:2});const s=store.getState();assert.equal(s.clips.length,5);assert.equal(s.clips.filter(c=>c.start===5).length,2);assert.equal(s.clips.find(c=>c.track==='audio'&&c.start===5).in,5);assert.equal(s.captions[0].start,7);assert.equal(s.markers[0].time,7);assert.equal(s.graphics[0].duration,10);await store.execute('edit.undo');assert.deepEqual(store.getState().clips,before.clips);assert.deepEqual(store.getState().graphics,before.graphics);
});
test('overwrite trims only target lane and keeps source offsets; top chooses a higher free layer',async()=>{const {store}=await fixture();await add(store,0,10,2);await add(store,0,10,2,'audio');await store.execute('timeline.place',{assetId:'asset_source',mode:'overwrite',track:'video',start:3,in:20,duration:2});const s=store.getState(),v=s.clips.filter(c=>c.track==='video').sort((a,b)=>a.start-b.start);assert.deepEqual(v.map(c=>[c.start,c.duration,c.in]),[[0,3,2],[3,2,20],[5,5,7]]);assert.equal(s.clips.find(c=>c.track==='audio').duration,10);const top=(await store.execute('timeline.place',{assetId:'asset_source',mode:'top',start:4,duration:2})).result;assert.equal(top.lane,1);await store.execute('timeline.layers',{ids:[top.id],action:'up'});assert.equal(store.getState().clips.find(c=>c.id===top.id).lane,2);const before=store.getState();await assert.rejects(store.execute('timeline.layers',{ids:[v[0].id],action:'down'}));assert.deepEqual(store.getState(),before);
});
test('continuous joins require matching source ranges and settings, keep exterior fades',async()=>{const {store}=await fixture(),a=await add(store,0,3,2),b=await add(store,3,4,5);await store.execute('timeline.update',{id:a.id,fadeIn:.2});await store.execute('timeline.update',{id:b.id,fadeOut:.3});const joined=(await store.execute('timeline.merge',{ids:[b.id,a.id]})).result;assert.equal(joined.duration,7);assert.equal(joined.fadeIn,.2);assert.equal(joined.fadeOut,.3);await store.execute('edit.undo');await store.execute('timeline.update',{id:b.id,in:7});const before=store.getState();await assert.rejects(store.execute('timeline.merge',{ids:[a.id,b.id]}));assert.deepEqual(store.getState(),before);});
test('sync points preserve clip contents and equal-power crossfades use handles without moving later material',async()=>{const {store}=await fixture(),a=await add(store,0,3,2,'audio'),b=await add(store,3,3,8,'audio'),v=await add(store,10,3,1);await store.execute('timeline.syncPoints',{referenceId:a.id,targetId:v.id,referencePoint:1.5,targetPoint:.5});assert.equal(store.getState().clips.find(c=>c.id===v.id).start,1);assert.equal(store.getState().clips.find(c=>c.id===v.id).in,1);
 await store.execute('audio.crossfade',{leftId:a.id,rightId:b.id,duration:.4});let s=store.getState(),l=s.clips[0],r=s.clips[1];assert.ok(Math.abs(l.duration-3.2)<1e-6);assert.equal(r.start,2.8);assert.equal(r.in,7.8);assert.equal(r.start+r.duration,6);assert.equal(r.lane,1);assert.ok(Math.abs(clipEnvelope(l,3)**2+clipEnvelope(r,3)**2-1)<.001);const before=s;await assert.rejects(store.execute('audio.syncApply',{targetId:v.id,start:1,projectId:s.id,updatedAt:'stale'}));assert.deepEqual(store.getState(),before);
});
test('waveform correlation distinguishes shifted speech envelopes from silence and repeated beats',()=>{let seed=42;const a=Array.from({length:1000},()=>{seed=(seed*1664525+1013904223)>>>0;return seed/2**32;});const b=Array(35).fill(0).concat(a.slice(0,-35));const r=correlateEnvelopes(a,b,{minLag:-100,maxLag:100});assert.equal(r.seconds,-.7);assert.ok(r.reliable);assert.throws(()=>correlateEnvelopes(Array(200).fill(0),Array(200).fill(0)));const beat=Array.from({length:1000},(_,i)=>i%50<5?1:0);assert.equal(correlateEnvelopes(beat,beat,{minLag:-100,maxLag:100}).reliable,false);});
test('all eight layered motion compositions validate; responsive duration preserves entry and exit times',async()=>{const {store}=await fixture();for(const [preset] of COMPOSITIONS){const r=await store.execute('graphics.compose',{preset,title:'要点／理由／結論',subtitle:'補足',duration:6});assert.ok(r.result.items.length>=4);}const g=store.getState().graphics[0],entry=g.keyframes[1].time,tail=g.duration-g.keyframes.at(-2).time;await store.execute('graphics.batch',{ids:[g.id],action:'duration',duration:10,protect:.5});const updated=store.getState().graphics[0];assert.equal(updated.keyframes[1].time,entry);assert.ok(Math.abs(10-updated.keyframes.at(-2).time-tail)<1e-6);await store.execute('graphics.batch',{ids:[g.id],action:'reverse'});assert.equal(store.getState().graphics[0].keyframes[0].opacity,0);await store.execute('graphics.batch',{ids:[g.id],action:'front'});assert.equal(store.getState().graphics.at(-1).id,g.id);const before=store.getState();await assert.rejects(store.execute('graphics.batch',{ids:[g.id],action:'duration',duration:.2,protect:.5}));assert.deepEqual(store.getState(),before);});
test('mixer validates dynamics and disabled compressor does not change filters',()=>{const defaults=mixerSettings();assert.ok(!mixerFilters(defaults,0).includes('acompressor'));defaults.tracks[0]={...defaults.tracks[0],compressor:true,thresholdDb:-24,ratio:4,attackMs:5};assert.match(mixerFilters(defaults,0),/acompressor=.*ratio=4/);assert.throws(()=>mixerSettings({tracks:Array(8).fill({ratio:0})}));assert.equal(clipStyle({...clipControls({blendMode:'screen',maskShape:'ellipse'}),start:0,duration:1},.5).mixBlendMode,'screen');});
test('real audio sync is read-only and reports a usable frame-quantized offset',async()=>{const {store,dataDir}=await fixture();let seed=52;const samples=Buffer.alloc(8000*6*2);for(let bin=0;bin<300;bin++){seed=(seed*1664525+1013904223)>>>0;const amplitude=.05+seed/2**32*.5;for(let i=0;i<160;i++)samples.writeInt16LE(Math.round(Math.sin((bin*160+i)*.22)*amplitude*32767),(bin*160+i)*2);}const aRaw=path.join(dataDir,'a.pcm'),bRaw=path.join(dataDir,'b.pcm');await fs.writeFile(aRaw,samples);await fs.writeFile(bRaw,Buffer.concat([Buffer.alloc(11200),samples]));const clips=[];for(const [i,file] of [aRaw,bRaw].entries()){const out=path.join(dataDir,`sync-${i}.wav`);await runProcess(FFMPEG,['-v','error','-y','-f','s16le','-ar','8000','-ac','1','-i',file,out]);const a=(await store.execute('asset.import',{path:out})).result;clips.push((await store.execute('timeline.add',{assetId:a.id,track:'audio',lane:i,start:2+i,duration:6})).result);}const before=store.getState(),r=await store.execute('audio.syncAnalyze',{referenceId:clips[0].id,targetId:clips[1].id,maxShift:3});assert.deepEqual(store.getState(),before);assert.ok(r.result.reliable);assert.ok(Math.abs(r.result.offset+1.7)<=1/25);await store.execute('audio.syncApply',{...r.result});assert.equal(store.getState().clips[1].start,r.result.start);});
test('masked blend modes and dynamics survive real low-memory export',async()=>{const {store,dataDir}=await fixture(),red=path.join(dataDir,'red.mp4'),blue=path.join(dataDir,'blue.mp4');for(const [file,color] of [[red,'red'],[blue,'blue']])await runProcess(FFMPEG,['-v','error','-y','-f','lavfi','-i',`color=${color}:s=160x160:r=25:d=1`,'-c:v','libx264','-threads','1',file]);const a=(await store.execute('asset.import',{path:red})).result,b=(await store.execute('asset.import',{path:blue})).result;await store.execute('timeline.add',{assetId:a.id,track:'video',start:0,duration:1});await store.execute('timeline.add',{assetId:b.id,track:'video',start:0,duration:1,lane:1,blendMode:'screen',maskShape:'ellipse',maskWidth:50,maskHeight:50});const tone=path.join(dataDir,'tone.wav');await runProcess(FFMPEG,['-v','error','-y','-f','lavfi','-i','sine=frequency=440:sample_rate=48000:duration=1','-af','volume=4',tone]);const ta=(await store.execute('asset.import',{path:tone})).result;await store.execute('timeline.add',{assetId:ta.id,track:'audio',start:0,duration:1});await store.execute('audio.track.update',{lane:0,compressor:true,thresholdDb:-20,ratio:3,kneeDb:18});const output=await exportProject(store.getState(),{format:'render',dataDir});const rgb=execFileSync(FFMPEG,['-v','error','-i',output.path,'-frames:v','1','-pix_fmt','rgb24','-f','rawvideo','pipe:1'],{windowsHide:true});const px=(x,y)=>[...rgb.subarray((y*160+x)*3,(y*160+x)*3+3)];assert.ok(px(80,80)[0]>200&&px(80,80)[2]>200,`screen center ${px(80,80)}`);assert.ok(px(5,5)[0]>200&&px(5,5)[2]<30,`mask corner ${px(5,5)}`);const pcm=execFileSync(FFMPEG,['-v','error','-ss','0.3','-i',output.path,'-t','0.3','-ac','1','-ar','8000','-f','s16le','pipe:1'],{windowsHide:true});let energy=0;for(let i=0;i+1<pcm.length;i+=2)energy+=(pcm.readInt16LE(i)/32768)**2;assert.ok(Math.sqrt(energy/(pcm.length/2))<.24,'compressor reduces the actual output level');await store.execute('asset.remove',{id:'asset_source'});await store.execute('background.apply',{preset:'blue'});const bundle=await store.execute('export.create',{format:'bundle'});const saved=path.join(bundle.result.path.slice(0,-4),'project.cutton.json');await store.execute('project.new',{name:'Reload'});await store.execute('project.open',{path:saved});const restored=store.getState();assert.ok(restored.clips.some(c=>c.maskShape==='ellipse'&&c.blendMode==='screen'));assert.equal(restored.audioMixer.tracks[0].compressor,true);assert.ok(restored.assets.some(a=>a.provenance?.kind==='cutton-background'));});
