import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {execFileSync} from 'node:child_process';import {Resvg} from '@resvg/resvg-js';import {createHash} from 'node:crypto';
import {createStore} from '../server/store.mjs';import {FFMPEG,runProcess,fileHash} from '../server/media.mjs';import {processOptions,PROCESS_PRESETS,processingFilters} from '../server/audio-processing-options.mjs';import {backgroundPresets,backgroundOptions,backgroundSvg} from '../server/background-presets.mjs';import {TEXT_MATERIALS} from '../server/text-materials.mjs';import {createOverlay} from '../server/overlays.mjs';import {captionsSvg} from '../server/caption-style.mjs';import {EXTRA_FONTS,BUNDLED_FONTS,ARTICLE_FONTS} from '../server/font-catalog.mjs';import {readFontFamily,renderFontFiles} from '../server/fonts.mjs';
async function fixture(){const dataDir=await fs.mkdtemp(path.join(os.tmpdir(),'cutton-studio-'));return {dataDir,store:await createStore({dataDir})};}
async function tone(store,dataDir,duration=4){const file=path.join(dataDir,'tone.wav');await runProcess(FFMPEG,['-v','error','-y','-f','lavfi','-i',`sine=frequency=440:sample_rate=48000:duration=${duration}`,'-c:a','pcm_s24le',file]);return (await store.execute('asset.import',{path:file})).result;}
function samples(file){const b=execFileSync(FFMPEG,['-v','error','-ss','0.5','-i',file,'-t','1','-ac','1','-ar','8000','-f','f32le','pipe:1'],{windowsHide:true});return Array.from({length:b.length/4},(_,i)=>b.readFloatLE(i*4));}
const frequency=s=>{let crossings=0;for(let i=1;i<s.length;i++)if(s[i-1]<0&&s[i]>=0)crossings++;return crossings*8000/s.length;};
test('studio options are bounded and filter injection cannot enter the graph',()=>{for(const bad of [{pitch:13},{noiseFloor:-1},{gate:'true'},{room:Infinity},{delayMs:'50,anull'}])assert.throws(()=>processOptions(bad));for(const p of Object.values(PROCESS_PRESETS))assert.ok(processingFilters(p.values).endsWith('latency=1'));});
test('real pitch processing preserves duration, original and repeat-edit source; cached takes and undo',async()=>{
 const {store,dataDir}=await fixture(),a=await tone(store,dataDir),hash=await fileHash(a.path),clip=(await store.execute('timeline.add',{assetId:a.id,track:'audio',start:1,in:.5,duration:2})).result;
 await store.execute('audio.process',{ids:[clip.id],options:{pitch:12,formant:false}});let s=store.getState(),processed=s.assets.find(a=>a.id===s.clips[0].assetId);assert.ok(Math.abs(frequency(samples(processed.path))-880)<4);assert.ok(Math.abs(processed.duration-2)<.001);assert.equal(s.clips[0].start,1);assert.equal(await fileHash(a.path),hash);assert.equal(processed.provenance.sourceIn,.5);
 const count=s.assets.length;await store.execute('audio.process',{ids:[clip.id],options:{pitch:12,formant:false}});assert.equal(store.getState().assets.length,count);
 await store.execute('audio.process',{ids:[clip.id],options:{pitch:0}});s=store.getState();const clean=s.assets.find(a=>a.id===s.clips[0].assetId);assert.equal(clean.provenance.sourceAssetId,a.id);assert.ok(Math.abs(frequency(samples(clean.path))-440)<3,'reprocessing uses original, not already shifted take');await store.execute('edit.undo');assert.equal(store.getState().clips[0].assetId,processed.id);
 const before=store.getState();await assert.rejects(store.execute('audio.process',{ids:[clip.id,'missing'],options:{pitch:1}}));assert.deepEqual(store.getState(),before);
 const bundle=await store.execute('export.create',{format:'bundle'});await store.execute('project.open',{path:path.join(bundle.result.path.slice(0,-4),'project.cutton.json')});s=store.getState();processed=s.assets.find(a=>a.id===s.clips[0].assetId);assert.equal(processed.provenance.kind,'cutton-audio-process');assert.ok(s.assets.some(a=>a.id===processed.provenance.sourceAssetId));await store.execute('audio.process',{ids:[s.clips[0].id],options:{pitch:0}});assert.ok(Math.abs(frequency(samples(store.getState().assets.at(-1).path))-440)<3);
});
test('studio DSP presets run on real PCM and FFT denoise reduces stationary noise',async()=>{
 const {dataDir}=await fixture(),source=path.join(dataDir,'noise.wav');await runProcess(FFMPEG,['-v','error','-y','-f','lavfi','-i','anoisesrc=d=3:r=48000:a=0.02:seed=17','-c:a','pcm_s24le',source]);
 for(const [id,p] of Object.entries(PROCESS_PRESETS)){await runProcess(FFMPEG,['-v','error','-y','-i',source,'-af',processingFilters({...p.values,delay:.1,delayMs:100}),'-t','2','-c:a','pcm_s24le',path.join(dataDir,id+'.wav')]);}
 const filtered=path.join(dataDir,'denoise.wav');await runProcess(FFMPEG,['-v','error','-y','-i',source,'-af',processingFilters({denoise:25,noiseFloor:-35}),'-c:a','pcm_s24le',filtered]);const rms=s=>Math.sqrt(s.reduce((a,v)=>a+v*v,0)/s.length);assert.ok(rms(samples(filtered))<rms(samples(source))*.8,'noise energy falls');
});
test('fractional speed processed clips retain source coverage and protect their original',async()=>{const {store,dataDir}=await fixture(),a=await tone(store,dataDir),c=(await store.execute('timeline.add',{assetId:a.id,track:'audio',duration:1/30,speed:.333})).result;await store.execute('audio.process',{ids:[c.id],options:{}});const s=store.getState(),processed=s.assets.at(-1);assert.ok(processed.duration+1e-6>=c.duration*c.speed);await assert.rejects(store.execute('asset.remove',{id:a.id}),/元音声/);const bundle=await store.execute('export.create',{format:'bundle'});await store.execute('project.open',{path:path.join(bundle.result.path.slice(0,-4),'project.cutton.json')});assert.equal(store.getState().clips[0].duration,c.duration);});
test('retime maintains relative A/V, caption words, motion and ripple marker alignment',async()=>{
 const {store,dataDir}=await fixture(),a=await tone(store,dataDir,8),c=(await store.execute('timeline.add',{assetId:a.id,track:'audio',start:2,duration:4})).result,cap=(await store.execute('caption.add',{text:'試験',start:3,duration:2,words:[{text:'試験',start:0,end:2}]})).result,g=(await store.execute('graphics.add',{type:'shape',start:2,duration:4,keyframes:[{time:0,x:0,y:50,scale:1,rotation:0,opacity:1},{time:4,x:100,y:50,scale:1,rotation:0,opacity:1}]})).result;
 await store.execute('marker.add',{time:6});const tail=(await store.execute('caption.add',{text:'次へ',start:7,duration:1})).result,before=store.getState();
 const items=[{type:'clip',id:c.id},{type:'caption',id:cap.id},{type:'graphic',id:g.id}];await store.execute('timeline.batch',{items,action:'retime',rate:2,ripple:true});let s=store.getState();assert.equal(s.clips[0].speed,2);assert.equal(s.clips[0].duration,2);assert.equal(s.captions[0].start,2.5);assert.equal(s.captions[0].words[0].end,1);assert.equal(s.graphics[0].keyframes[1].time,2);assert.equal(s.markers[0].time,4);assert.equal(s.captions.find(c=>c.id===tail.id).start,5);await store.execute('edit.undo');assert.deepEqual(store.getState().clips,before.clips);
 const untouched=store.getState();await assert.rejects(store.execute('timeline.batch',{items:[items[0]],action:'retime',rate:2,ripple:true}),/重なる/);assert.deepEqual(store.getState(),untouched);await assert.rejects(store.execute('timeline.batch',{items,action:'retime',rate:0}));assert.deepEqual(store.getState(),untouched);
});
test('bulk duplicate keeps internal graphic links; deletion and failure are atomic',async()=>{
 const {store,dataDir}=await fixture(),a=await tone(store,dataDir),c=(await store.execute('timeline.add',{assetId:a.id,track:'audio',duration:2})).result,parent=(await store.execute('graphics.add',{type:'null',duration:2})).result,child=(await store.execute('graphics.add',{type:'vector',shape:'rect',duration:2,parentId:parent.id})).result;
 const items=[{id:c.id,type:'clip'},{id:parent.id,type:'graphic'},{id:child.id,type:'graphic'}],r=await store.execute('timeline.batch',{items,action:'duplicate'});let s=store.getState();assert.equal(s.clips[1].start,2);assert.equal(s.graphics[3].parentId,s.graphics[2].id);const before=store.getState();await assert.rejects(store.execute('timeline.batch',{items,action:'duplicate',at:1}));assert.deepEqual(store.getState(),before);await store.execute('timeline.batch',{items:r.result.items,action:'remove'});assert.equal(store.getState().clips.length,1);await store.execute('edit.undo');assert.equal(store.getState().clips.length,2);
});
test('all backgrounds rasterize distinctly and custom colors, pattern and vignette persist',async()=>{
 const hashes=new Set();for(const p of backgroundPresets){const png=new Resvg(backgroundSvg(p.id,160,90)).render().asPng();hashes.add(createHash('sha256').update(png).digest('hex'));}assert.equal(hashes.size,10);assert.throws(()=>backgroundOptions('blue',{a:'url(file)'}));assert.throws(()=>backgroundOptions('blue',{density:100}));
 const {store,dataDir}=await fixture(),a=await tone(store,dataDir);await store.execute('timeline.add',{assetId:a.id,track:'audio',duration:2});await store.execute('background.apply',{preset:'sunset',options:{a:'#12abcd',pattern:'grid',vignette:.4}});const asset=store.getState().assets.at(-1);assert.equal(asset.provenance.options.a,'#12abcd');assert.equal(asset.width,1920);assert.equal(asset.height,1080);
});
test('eight text materials render with real fonts, preserve word timing and reject invalid effects',async()=>{
 const fontFiles=await renderFontFiles(['Source Han Sans JP']),hashes=new Set();for(const p of TEXT_MATERIALS){const c=createOverlay('caption',{text:'光沢',x:50,y:50,fontSize:48,duration:2,fontFamily:'Source Han Sans JP',words:[{text:'光沢',start:0,end:2}],...p.values});assert.equal(c.words[0].end,2);const svg=captionsSvg({width:320,height:160,captions:[c]},1),png=new Resvg(svg,{font:{fontFiles,loadSystemFonts:false}}).render().asPng();assert.ok(png.length>600);hashes.add(createHash('sha256').update(png).digest('hex'));}assert.equal(hashes.size,TEXT_MATERIALS.length);assert.throws(()=>createOverlay('caption',{text:'A',glow:50}));assert.throws(()=>createOverlay('caption',{text:'A',gradientMiddleColor:'red'}));
 const {store}=await fixture(),c=(await store.execute('caption.add',{text:'光沢',...TEXT_MATERIALS[2].values})).result;await store.execute('caption.update',{id:c.id,gloss:.4});assert.equal(store.getState().captions[0].gloss,.4);await store.execute('edit.undo');assert.equal(store.getState().captions[0].gloss,.65);
});
test('eight additional Japanese fonts and their licenses are actually bundled',async()=>{assert.equal(EXTRA_FONTS.length,8);assert.equal(BUNDLED_FONTS.length,13);assert.equal(ARTICLE_FONTS.length,35);for(const f of EXTRA_FONTS){const b=await fs.readFile(new URL('../public/fonts/'+f.files[0],import.meta.url));assert.equal(readFontFamily(b),f.family);assert.ok((await renderFontFiles([f.family])).length);}});
