import {mixerSettings,trackGain,balanceGains,dbGain} from '../server/audio-mixer.mjs';
import {clipEnvelope} from '../server/clip-effects.mjs';
let context,master,limiter,settings=mixerSettings();const sources=new WeakMap(),live=new Set();
function ensure(){if(context)return;context=new AudioContext();master=context.createGain();limiter=context.createDynamicsCompressor();limiter.threshold.value=-.2;limiter.knee.value=0;limiter.ratio.value=20;limiter.attack.value=.003;limiter.release.value=.08;master.connect(limiter).connect(context.destination);}
const smooth=(param,v)=>param.setTargetAtTime(v,context.currentTime,.01);
function configure(n){const t=settings.tracks[n.lane],[l,r]=balanceGains(t.balance);smooth(n.gain.gain,trackGain(settings,n.lane));smooth(n.left.gain,l);smooth(n.right.gain,r);smooth(n.low.gain,t.lowDb);smooth(n.mid.gain,t.midDb);smooth(n.high.gain,t.highDb);}
export function setMixer(value){settings=mixerSettings(value);if(context){smooth(master.gain,dbGain(settings.masterDb));live.forEach(configure);}}
export function connectAudio(element,lane){ensure();let n=sources.get(element);if(!n){const source=context.createMediaElementSource(element),clip=context.createGain(),low=context.createBiquadFilter(),mid=context.createBiquadFilter(),high=context.createBiquadFilter(),gain=context.createGain(),split=context.createChannelSplitter(2),left=context.createGain(),right=context.createGain(),merge=context.createChannelMerger(2),meter=context.createAnalyser();low.type='lowshelf';low.frequency.value=200;mid.type='peaking';mid.frequency.value=1000;mid.Q.value=1;high.type='highshelf';high.frequency.value=4000;clip.channelCount=2;clip.channelCountMode='explicit';source.connect(clip).connect(low).connect(mid).connect(high).connect(split);split.connect(left,0);split.connect(right,1);left.connect(merge,0,0);right.connect(merge,0,1);merge.connect(gain).connect(meter);meter.fftSize=256;n={source,clip,low,mid,high,gain,left,right,meter,lane};sources.set(element,n);}n.lane=lane;n.meter.connect(master);live.add(n);configure(n);smooth(master.gain,dbGain(settings.masterDb));return {update(clip,time,playing){n.lane=clip.lane||0;configure(n);smooth(n.clip.gain,(clip.gain??1)*clipEnvelope(clip,time));element.volume=1;if(playing&&context.state==='suspended')context.resume().catch(()=>{});},disconnect(){n.meter.disconnect();live.delete(n);}};}
const meterData=new Float32Array(256);
export function peaks(){const values=Array(8).fill(0);if(!context||context.state!=='running')return values;live.forEach(n=>{n.meter.getFloatTimeDomainData(meterData);for(const v of meterData)values[n.lane]=Math.max(values[n.lane],Math.abs(v));});return values;}
