import React,{useEffect,useRef} from 'react';
import {clipStyle} from '../server/clip-effects.mjs';
import {keyRGB,keyDefaults} from '../server/chroma-key.mjs';
export default function ChromaPreview({source,clip,clock,width,onError}){
 const canvas=useRef(null),current=useRef(clip);current.current=clip;
 useEffect(()=>{const el=canvas.current,gl=el.getContext('webgl',{alpha:true,premultipliedAlpha:false,antialias:false});if(!gl){onError('クロマキーのプレビューにはWebGLが必要です。書き出しは利用できます。');return;}
  const shader=(type,code)=>{const s=gl.createShader(type);gl.shaderSource(s,code);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s;};let program,texture,buffer,shaders=[];
  try{shaders=[shader(gl.VERTEX_SHADER,'attribute vec2 pos; varying vec2 uv; void main(){uv=(pos+1.0)*0.5;uv.y=1.0-uv.y;gl_Position=vec4(pos,0.0,1.0);}'),shader(gl.FRAGMENT_SHADER,'precision mediump float; varying vec2 uv; uniform sampler2D image; uniform vec3 key; uniform float similarity; uniform float blend; uniform float spill; void main(){vec4 c=texture2D(image,uv);float d=distance(c.rgb,key)/sqrt(3.0);float a=blend>0.00001?clamp((d-similarity)/blend,0.0,1.0):step(similarity,d);if(key.g>key.r&&key.g>key.b)c.g-=spill*max(0.0,c.g-max(c.r,c.b));else if(key.b>key.r&&key.b>key.g)c.b-=spill*max(0.0,c.b-max(c.r,c.g));gl_FragColor=vec4(c.rgb,c.a*a);}')];program=gl.createProgram();shaders.forEach(s=>gl.attachShader(program,s));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error('Shader link failed');gl.useProgram(program);buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'pos');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);}catch(error){onError('クロマキープレビューを初期化できません: '+error.message);return;}
  let lastTime=-1,lastClip=null;const draw=()=>{const media=source.current,c={...keyDefaults,...current.current};if(!media||!(media.videoWidth||media.naturalWidth))return;const style=clipStyle(c,clock.time);style.filter=style.filter.replace(/blur\(([^p]+)px\)/,(_,v)=>`blur(${Number(v)*el.parentElement.clientWidth/width}px)`);Object.assign(el.style,style);if(lastTime===media.currentTime&&lastClip===current.current)return;lastTime=media.currentTime;lastClip=current.current;const w=media.videoWidth||media.naturalWidth,h=media.videoHeight||media.naturalHeight;if(el.width!==w)el.width=w;if(el.height!==h)el.height=h;gl.viewport(0,0,el.width,el.height);try{gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,media);gl.uniform3fv(gl.getUniformLocation(program,'key'),keyRGB(c.keyColor).map(v=>v/255));gl.uniform1f(gl.getUniformLocation(program,'similarity'),c.keySimilarity);gl.uniform1f(gl.getUniformLocation(program,'blend'),c.keyBlend);gl.uniform1f(gl.getUniformLocation(program,'spill'),c.keySpill);gl.drawArrays(gl.TRIANGLES,0,6);}catch{onError('この素材をクロマキープレビューへ読み込めません。');}};
  draw();const off=clock.subscribe(draw),media=source.current;media?.addEventListener('loadeddata',draw);media?.addEventListener('seeked',draw);media?.addEventListener('load',draw);return()=>{off();media?.removeEventListener('loadeddata',draw);media?.removeEventListener('seeked',draw);media?.removeEventListener('load',draw);gl.deleteTexture(texture);gl.deleteBuffer(buffer);gl.deleteProgram(program);shaders.forEach(s=>gl.deleteShader(s));};
 },[source,clock,width,onError]);
 useEffect(()=>clock.notify(),[clip,clock]);
 return <canvas ref={canvas} className="media-layer chroma-canvas" style={clipStyle(clip,clock.time)}/>;
}
