import BackgroundDesigner from './background-designer';
import React,{useMemo,useState} from 'react';
import {Button,Field} from './ui';
import {captionIssues,captionLooks} from '../server/caption-editing.mjs';
import {backgroundPresets,backgroundSvg} from '../server/background-presets.mjs';

export function CaptionReview({state,onSelect,clock,run,busy}){
 const issues=useMemo(()=>captionIssues(state),[state.captions,state.width]);
 return <details className="finishing-panel"><summary>字幕の読みやすさを確認 <span>{issues.length}件</span></summary><p className="muted-copy">短すぎる表示・語尾だけの字幕・重なりを確認できます。文章の意味や聞き取りの正確さは個別に確認してください。</p>{issues.length===0?<p>短い語尾・重なり・表示時間の問題は見つかりませんでした。</p>:<div className="caption-issues">{issues.map(c=><article key={c.id}><button type="button" onClick={()=>{onSelect({type:'caption',id:c.id});clock.seek(c.start);}}>{c.start.toFixed(2)}s　{c.text}</button><small>{c.reasons.join(' / ')}</small><div className="button-row">{c.previousId&&<Button disabled={!!busy} onClick={async()=>{const r=await run('caption.merge',{ids:[c.previousId,c.id]});if(r)onSelect({type:'caption',id:r.result.id});}}>前と結合</Button>}{c.nextId&&<Button disabled={!!busy} onClick={async()=>{const r=await run('caption.merge',{ids:[c.id,c.nextId]});if(r)onSelect({type:'caption',id:r.result.id});}}>次と結合</Button>}</div></article>)}</div>}</details>;
}
export function CaptionBoundaryTools({item,state,clock,run,busy,onSelect}){
 const [index,setIndex]=useState(0),[useClock,setUseClock]=useState(false),sorted=[...state.captions].sort((a,b)=>a.start-b.start),i=sorted.findIndex(c=>c.id===item.id);
 return <details className="finishing-panel"><summary>字幕の区切り・強調</summary><div className="button-row">{Object.entries(captionLooks).map(([preset,l])=><Button key={preset} disabled={!!busy} onClick={()=>run('caption.look',{ids:[item.id],preset})}>{l.name}</Button>)}</div><p className="muted-copy">保存済みの文章で分割位置をクリックします。動詞の語尾や固有名詞の途中では切らず、長い文章はテキスト欄で改行してください。</p><textarea aria-label="字幕の分割位置" readOnly value={item.text} rows={3} onSelect={e=>setIndex(e.target.selectionStart)}/><small>{index>0&&index<item.text.length?`${item.text.slice(0,index)} ｜ ${item.text.slice(index)}`:'分割する文字位置を選択'}</small><label className="checkbox-field"><input type="checkbox" checked={useClock||!item.words?.length} disabled={!item.words?.length} onChange={e=>setUseClock(e.target.checked)}/>再生ヘッドの時刻で分割</label><div className="button-row"><Button disabled={!!busy||index<=0||index>=item.text.length} onClick={async()=>{const r=await run('caption.split',{id:item.id,index,...(useClock||!item.words?.length?{at:clock.time}:{})});if(r)onSelect({type:'caption',id:r.result.captions[1].id});}}>ここで分割</Button>{i>0&&<Button disabled={!!busy} onClick={async()=>{const r=await run('caption.merge',{ids:[sorted[i-1].id,item.id]});if(r)onSelect({type:'caption',id:r.result.id});}}>前の字幕と結合</Button>}{i<sorted.length-1&&<Button disabled={!!busy} onClick={()=>run('caption.merge',{ids:[item.id,sorted[i+1].id]})}>次の字幕と結合</Button>}</div></details>;
}
export function BackgroundPanel({state,run,busy}){
 const [options,setOptions]=useState({}),[preset,setPreset]=useState('blue'),[replace,setReplace]=useState(()=>state.clips.find(c=>c.track==='video'&&state.assets.some(a=>a.id===c.assetId&&(a.provenance?.kind==='cutton-background'||a.kind==='image'&&a.name.startsWith('背景'))))?.id||''),[crop,setCrop]=useState(false),[lane,setLane]=useState(()=>state.clips.find(c=>c.track==='video'&&state.assets.some(a=>a.id===c.assetId&&a.kind==='video'))?.lane||0),[trim,setTrim]=useState({top:0,bottom:0,left:0,right:0}),[message,setMessage]=useState('');
 const images=state.clips.filter(c=>c.track==='video'&&state.assets.find(a=>a.id===c.assetId)?.kind==='image'),lanes=[...new Set(state.clips.filter(c=>c.track==='video').map(c=>c.lane||0))].sort();
 return <details className="finishing-panel"><summary>背景を整える</summary><div className="background-choices">{backgroundPresets.map(p=><button type="button" key={p.id} aria-pressed={preset===p.id} className={preset===p.id?'active':''} onClick={()=>{setPreset(p.id);setOptions({});}}><img alt="" src={'data:image/svg+xml,'+encodeURIComponent(backgroundSvg(p.id,160,90))}/><span>{p.name}</span></button>)}</div><BackgroundDesigner preset={preset} options={options} onChange={setOptions}/><Field label="背景の配置"><select value={replace} onChange={e=>setReplace(e.target.value)}><option value="">新規に最下段へ追加</option>{images.map(c=><option value={c.id} key={c.id}>V{(c.lane||0)+1} の画像を差し替え · {state.assets.find(a=>a.id===c.assetId)?.name}</option>)}</select></Field><p className="muted-copy">新規追加では映像トラックを1段上に移動します。背景は画像として保存され、書き出しにも反映されます。</p><label className="checkbox-field"><input type="checkbox" checked={crop} onChange={e=>setCrop(e.target.checked)}/>映像の外側の余白を透過する</label>{crop&&<><Field label="余白を透過する映像トラック"><select value={lane} onChange={e=>setLane(Number(e.target.value))}>{lanes.map(n=><option key={n} value={n}>V{n+1}</option>)}</select></Field><div className="effect-fields">{[['top','上'],['bottom','下'],['left','左'],['right','右']].map(([key,label])=><Field key={key} label={`${label} (%)`}><input type="number" min="0" max="90" step=".1" value={trim[key]} onChange={e=>setTrim({...trim,[key]:Number(e.target.value)})}/></Field>)}</div><p className="muted-copy">黒帯の幅に合わせて調整してください。元素材は変更されません。</p></>}<Button className="primary full-width" disabled={!!busy||!state.clips.length} onClick={async()=>{const r=await run('background.apply',{preset,options,...(replace?{replaceClipId:replace}:{}),...(crop?{foregroundLane:lane,...trim}:{})});if(r){setReplace(r.result.clipId);setMessage('背景を保存しました。戻す操作で取り消せます。');if(!replace)setLane(lane+1);}}}>背景を適用</Button>{message&&<p role="status">{message}</p>}</details>;
}
export function BgmPanel({state,run,busy}){
 const [assetId,setAssetId]=useState(''),[voiceLane,setVoiceLane]=useState(0),[level,setLevel]=useState(-30),[ducking,setDucking]=useState(true),[fadeIn,setFadeIn]=useState(2),[fadeOut,setFadeOut]=useState(4),[message,setMessage]=useState('');
 const assets=state.assets.filter(a=>a.kind==='audio'||a.hasAudio),lanes=[...new Set(state.clips.filter(c=>c.track==='audio'&&!c.muted).map(c=>c.lane||0))].sort(),chosenVoice=lanes.includes(voiceLane)?voiceLane:lanes[0]??0;
 return <details className="finishing-panel"><summary>BGMを動画の長さに合わせる</summary><p className="muted-copy">メディアに取り込んだ曲を選択します。短い曲は継ぎ目を重ねてループし、別の音声素材として空きトラックへ配置します。</p><Field label="BGM素材"><select value={assetId} onChange={e=>setAssetId(e.target.value)}><option value="">曲を選択</option>{assets.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><label className="checkbox-field"><input type="checkbox" checked={ducking} onChange={e=>setDucking(e.target.checked)}/>声があるときにBGMを下げる</label>{ducking&&<Field label="ナレーションのトラック"><select value={chosenVoice} onChange={e=>setVoiceLane(Number(e.target.value))}>{lanes.map(n=><option key={n} value={n}>A{n+1}</option>)}</select></Field>}<Field label="BGMの基本音量"><select value={level} onChange={e=>setLevel(Number(e.target.value))}><option value={-34}>小さめ</option><option value={-30}>標準</option><option value={-26}>大きめ</option></select></Field><div className="field-row">{[['入りのフェード（秒）',fadeIn,setFadeIn],['終わりのフェード（秒）',fadeOut,setFadeOut]].map(([label,value,set])=><Field key={label} label={label}><input type="number" min="0" max="30" step=".5" value={value} onChange={e=>set(Number(e.target.value))}/></Field>)}</div><Button className="primary full-width" disabled={!!busy||!assetId||!state.clips.length||(ducking&&!lanes.length)} onClick={async()=>{setMessage('');const r=await run('audio.prepareBgm',{assetId,voiceLane:chosenVoice,level,ducking,fadeIn,fadeOut});if(r)setMessage(`A${r.result.lane+1} にBGMを追加しました。`);}}>{busy==='audio.prepareBgm'?'BGMを調整しています…':'BGMを作って配置'}</Button>{message&&<p role="status">{message}</p>}<p className="muted-copy">声の配置を変更した場合は作り直してください。曲の利用条件は元の配布元に従ってください。</p></details>;
}
export function MotionLayoutPanel({clock,run,busy}){
 const [preset,setPreset]=useState('compare'),[texts,setTexts]=useState(['伝統','現代','共感']),[duration,setDuration]=useState(6),[y,setY]=useState(18);const count=preset==='compare'?2:3;
 return <details className="finishing-panel"><summary>比較・段階表示のモーション</summary><Field label="構成"><select value={preset} onChange={e=>setPreset(e.target.value)}><option value="compare">左右から表示する比較</option><option value="steps">3つの要点を順番に表示</option></select></Field>{texts.slice(0,count).map((text,i)=><Field key={i} label={`項目 ${i+1}`}><input maxLength={60} value={text} onChange={e=>setTexts(texts.map((s,j)=>i===j?e.target.value:s))}/></Field>)}<div className="field-row"><Field label="長さ（秒）"><input type="number" min="2" max="60" step=".5" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></Field><Field label="縦位置（%）"><input type="number" min="10" max="90" value={y} onChange={e=>setY(Number(e.target.value))}/></Field></div><Button disabled={!!busy||texts.slice(0,count).some(t=>!t.trim())} onClick={()=>run('graphics.layout',{preset,texts:texts.slice(0,count),start:clock.time,duration,y})}>再生位置に追加</Button><p className="muted-copy">追加後は各カードの文字・位置・キーフレームを個別に調整できます。</p></details>;
}
