import {BgmPanel} from './finishing-panels';
import SoundLibrary from './sound-library';
import React,{useEffect,useRef,useState} from 'react';
import {mixerSettings} from '../server/audio-mixer.mjs';
import {setMixer,peaks} from './audio-engine';
import {sfxPresets,synthSound} from '../server/sfx.mjs';
function Meter({lane}){const ref=useRef(null);useEffect(()=>{const timer=setInterval(()=>{if(ref.current)ref.current.style.width=`${Math.max(0,Math.min(100,(20*Math.log10(peaks()[lane]||.00001)+60)/60*100))}%`;},80);return()=>clearInterval(timer);},[lane]);return <div className="audio-meter" aria-label={`A${lane+1} 信号レベル`}><i ref={ref}/></div>;}
export function MixerPanel({state,run,busy}){
 const [draft,setDraft]=useState(()=>mixerSettings(state.audioMixer)),pending=useRef(false);
 useEffect(()=>setDraft(mixerSettings(state.audioMixer)),[state.audioMixer,state.id]);
 useEffect(()=>()=>setMixer(state.audioMixer),[state.audioMixer]);
 const change=(lane,key,value)=>{const next=structuredClone(draft);if(lane===null)next.masterDb=value;else next.tracks[lane][key]=value;setDraft(next);setMixer(next);return next;};
 const save=async(lane,value=draft)=>{if(pending.current)return;pending.current=true;const response=await run(lane===null?'audio.master.update':'audio.track.update',lane===null?{masterDb:value.masterDb}:{lane,...value.tracks[lane]});pending.current=false;if(!response){setDraft(mixerSettings(state.audioMixer));setMixer(state.audioMixer);}};
 const slider=(lane,key,label,min,max,step=1)=>{const value=lane===null?draft.masterDb:draft.tracks[lane][key];return <label className="mixer-control">{label}<output>{value.toFixed(key==='balance'?2:1)}{key.endsWith('Hz')?' Hz':['balance','midQ'].includes(key)?'':' dB'}</output><input aria-label={`${lane===null?'マスター':'A'+(lane+1)} ${label}`} type="range" min={min} max={max} step={step} value={value} disabled={busy} onChange={e=>change(lane,key,Number(e.target.value))} onPointerUp={()=>save(lane)} onKeyUp={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End','PageUp','PageDown'].includes(e.key))save(lane);}} onBlur={()=>{if(JSON.stringify(draft)!==JSON.stringify(mixerSettings(state.audioMixer))&&!busy)save(lane);}}/></label>;};
 return <section className="mixer-panel"><h3>オーディオトラックミキサー</h3><BgmPanel state={state} run={run} busy={busy}/><p className="muted-copy">フェーダーを動かすと再生に反映。離すと保存します。</p><div className="master-strip">{slider(null,'masterDb','マスター',-60,12,.5)}</div>{draft.tracks.map((t,lane)=><div className="channel-strip" key={lane}><header><strong>A{lane+1}</strong><span>{state.clips.filter(c=>c.track==='audio'&&(c.lane||0)===lane).length} クリップ</span><button disabled={busy} className={t.mute?'active':''} aria-pressed={t.mute} aria-label={`A${lane+1} ミュート`} onClick={()=>save(lane,change(lane,'mute',!t.mute))}>M</button><button disabled={busy} className={t.solo?'active':''} aria-pressed={t.solo} aria-label={`A${lane+1} ソロ`} onClick={()=>save(lane,change(lane,'solo',!t.solo))}>S</button></header><Meter lane={lane}/>{slider(lane,'volumeDb','音量',-60,12,.5)}{slider(lane,'balance','L ← バランス → R',-1,1,.05)}<details><summary>EQ・周波数・ノイズ帯域</summary>{slider(lane,'lowDb','低域ゲイン',-12,12,.5)}{slider(lane,'midDb','中域ゲイン',-12,12,.5)}{slider(lane,'highDb','高域ゲイン',-12,12,.5)}{slider(lane,'lowHz','低域の周波数',20,2000,10)}{slider(lane,'midHz','中域の周波数',100,16000,10)}{slider(lane,'midQ','中域のQ（幅）',.1,12,.1)}{slider(lane,'highHz','高域の周波数',1000,20000,100)}{['highpass','lowpass'].map(key=><React.Fragment key={key}><label><input type="checkbox" checked={t[key]} disabled={busy} onChange={e=>save(lane,change(lane,key,e.target.checked))}/>{key==='highpass'?'低音の振動を除く（ハイパス）':'高音を抑える（ローパス）'}</label>{t[key]&&slider(lane,key+'Hz','カット周波数',key==='highpass'?20:1000,key==='highpass'?2000:20000,10)}</React.Fragment>)}</details></div>)}</section>;
}
export function SoundPanel({state,clock,run,busy,onUploaded}){
 const [preset,setPreset]=useState('whoosh'),[duration,setDuration]=useState(1),[frequency,setFrequency]=useState(440),[levelDb,setLevelDb]=useState(-12),[error,setError]=useState(''),[playing,setPlaying]=useState(false),audio=useRef(null);
 const stop=()=>{audio.current?.close().catch(()=>{});audio.current=null;setPlaying(false);};useEffect(()=>()=>{audio.current?.close().catch(()=>{});},[]);
 const options={preset,duration,frequency,levelDb};
 const audition=async()=>{stop();try{const {samples,rate}=synthSound(options),context=new AudioContext();audio.current=context;await context.resume();const buffer=context.createBuffer(1,samples.length,rate);buffer.copyToChannel(samples,0);const source=context.createBufferSource();source.buffer=buffer;source.connect(context.destination);source.onended=()=>{if(audio.current===context){audio.current=null;setPlaying(false);}context.close().catch(()=>{});};source.start();setPlaying(true);setError('');}catch(e){stop();setError(e.message);}};
 return <section className="sound-panel"><SoundLibrary state={state} clock={clock} run={run} busy={busy} onUploaded={onUploaded}/><h3>内蔵の効果音を作る</h3><p className="muted-copy">内蔵シンセサイザーで作成。長さ・音程・音量を調整して、再生ヘッド位置の空き音声トラックに追加します。</p><label>サウンド<select value={preset} onChange={e=>setPreset(e.target.value)}>{Object.entries(sfxPresets).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>{[['長さ (秒)',duration,setDuration,.1,8,.1],['基準の音程 (Hz)',frequency,setFrequency,100,2000,10],['音量 (dBFS)',levelDb,setLevelDb,-60,0,1]].map(([label,value,set,min,max,step])=><label key={label}>{label}<input type="number" min={min} max={max} step={step} value={value} onChange={e=>set(Number(e.target.value))}/></label>)}<div className="button-row"><button className="button" onClick={playing?stop:audition}>{playing?'試聴を停止':'▶ 試聴'}</button><button className="button primary" disabled={busy} onClick={async()=>{stop();const response=await run('sfx.create',{...options,start:clock.time});if(response)setError('');}}>＋ タイムラインに追加</button></div>{error&&<p className="inline-error">{error}</p>}</section>;
}
