import React,{useState,useEffect} from 'react';
import {Button,Field} from './ui';
import {COMPOSITIONS} from '../server/motion-catalog.mjs';
const Num=({label,value,set,min=0,max=86400,step=.01})=><Field label={label}><input type="number" value={value} min={min} max={max} step={step} onChange={e=>set(Number(e.target.value))}/></Field>;
export function ProTimelineTools({state,clock,items,run,busy}){
 const [mode,setMode]=useState('roll'),[edge,setEdge]=useState('out'),[frames,setFrames]=useState(1),[assetId,setAsset]=useState(''),[track,setTrack]=useState('video'),[lane,setLane]=useState(0),[sourceIn,setSourceIn]=useState(0),[duration,setDuration]=useState(3),[markA,setA]=useState(0),[markB,setB]=useState(0),[result,setResult]=useState(null),[swap,setSwap]=useState(false),[maxShift,setMaxShift]=useState(10),[fade,setFade]=useState(.4),[motionDuration,setMotionDuration]=useState(6),[protect,setProtect]=useState(.5),[gap,setGap]=useState(.15);
 const clips=items.filter(i=>i.type==='clip').map(i=>state.clips.find(c=>c.id===i.id)).filter(Boolean),graphics=items.filter(i=>i.type==='graphic').map(i=>i.id),one=clips.length===1?clips[0]:null,pair=clips.length===2?(swap?[clips[1],clips[0]]:clips):[],signature=clips.map(c=>c.id).join('|');
 useEffect(()=>{setResult(null);setA(0);setB(0);setSwap(false);},[signature,state.id]);
 const nudge=d=>run('timeline.align',{items,mode:'offset',at:d/state.fps}),trim=d=>run('timeline.trim',{id:one.id,mode,edge,frames:d}),clipName=c=>`${c.track==='video'?'V':'A'}${(c.lane||0)+1} · ${state.assets.find(a=>a.id===c.assetId)?.name}`;
 return <div className="pro-tools"><details name="pro-timeline"><summary>精密編集・レイヤー</summary><div className="pro-tool-body"><div className="button-row"><span>{items.length} 要素</span><Button disabled={busy||!items.length} onClick={()=>nudge(-1)}>−1フレーム</Button><Button disabled={busy||!items.length} onClick={()=>nudge(1)}>＋1フレーム</Button><Button disabled={busy||!items.length} onClick={()=>nudge(-10)}>−10</Button><Button disabled={busy||!items.length} onClick={()=>nudge(10)}>＋10</Button></div><div className="pro-form-row"><Field label="トリム方法"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="roll">ロール · 隣と尺を交換</option><option value="ripple">リップル · 同じトラックの後続を移動</option><option value="slide">スライド · 前後を調整して移動</option><option value="slip">スリップ · 使用範囲だけ変更</option></select></Field><Field label="編集点"><select value={edge} onChange={e=>setEdge(e.target.value)}><option value="out">終点</option><option value="in">始点</option></select></Field><Num label="フレーム数" value={frames} set={setFrames} min={1} max={1000} step={1}/><Button disabled={busy||!one||!Number.isInteger(frames)||frames<1} onClick={()=>trim(-frames)}>手前へ</Button><Button disabled={busy||!one||!Number.isInteger(frames)||frames<1} onClick={()=>trim(frames)}>後ろへ</Button></div><p className="muted-copy">トリムは1クリップを選択。リップルは同じトラックのみ動かします。複数選択中はドラッグでも相対的な位置を保って動かせます。</p><div className="button-row">{[['up','上のレイヤーへ'],['down','下のレイヤーへ'],['mute','非表示／ミュート'],['unmute','再表示／解除']].map(([action,label])=><Button key={action} disabled={busy||!clips.length} onClick={()=>run('timeline.layers',{ids:clips.map(c=>c.id),action})}>{label}</Button>)}<Button disabled={busy||clips.length<2} onClick={()=>run('timeline.merge',{ids:clips.map(c=>c.id)})}>連続カットを結合</Button></div><small>結合は同じ素材の連続部分が対象です。素材や効果の異なるクリップは、レイヤーとして重ねて合成できます。</small></div></details>
 <details name="pro-timeline"><summary>挿入・上書き・かぶせ</summary><div className="pro-tool-body"><div className="pro-form-row"><Field label="取り込み済み素材"><select value={assetId} onChange={e=>setAsset(e.target.value)}><option value="">素材を選択</option>{state.assets.filter(a=>track==='audio'?a.hasAudio||a.kind==='audio':['video','image'].includes(a.kind)).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="種類"><select value={track} onChange={e=>{setTrack(e.target.value);setAsset('');}}><option value="video">映像</option><option value="audio">音声</option></select></Field><Field label="配置先"><select value={lane} onChange={e=>setLane(Number(e.target.value))}>{Array.from({length:8},(_,i)=><option value={i} key={i}>{track==='video'?'V':'A'}{i+1}</option>)}</select></Field><Num label="素材の開始（秒）" value={sourceIn} set={setSourceIn}/><Num label="使用する尺（秒）" value={duration} set={setDuration} min={1/state.fps}/></div><div className="button-row">{[['insert','再生位置に挿入'],['overwrite','範囲を上書き'],['top','上に重ねる']].map(([m,label])=><Button key={m} disabled={busy||!assetId||duration<=0} onClick={()=>run('timeline.place',{mode:m,assetId,track,lane,start:clock.time,in:sourceIn,duration})}>{label}</Button>)}</div><p className="muted-copy">挿入は全トラックと字幕・モーション・マーカーを連動。上書きは指定トラックのみ。かぶせは同時刻の素材より上の空きトラックを使います。</p></div></details>
 <details name="pro-timeline"><summary>同期・クロスフェード</summary><div className="pro-tool-body">{pair.length===2?<><p>基準：{clipName(pair[0])}<br/>動かす対象：{clipName(pair[1])}</p><Button onClick={()=>{setSwap(!swap);setResult(null);}}>基準と対象を交換</Button><div className="pro-form-row"><Num label="基準のクリップ内時刻（秒）" value={markA} set={setA} max={pair[0].duration}/><Button onClick={()=>setA(Math.max(0,Math.min(pair[0].duration,clock.time-pair[0].start)))}>再生位置を基準点に</Button><Num label="対象のクリップ内時刻（秒）" value={markB} set={setB} max={pair[1].duration}/><Button onClick={()=>setB(Math.max(0,Math.min(pair[1].duration,clock.time-pair[1].start)))}>再生位置を対象点に</Button><Button disabled={busy} onClick={()=>run('timeline.syncPoints',{referenceId:pair[0].id,targetId:pair[1].id,referencePoint:markA,targetPoint:markB})}>2つの点を合わせる</Button></div><div className="pro-form-row"><Num label="音声同期の探索幅（±秒）" value={maxShift} set={setMaxShift} min={.1} max={30}/><Button disabled={busy} onClick={async()=>{setResult(null);const r=await run('audio.syncAnalyze',{referenceId:pair[0].id,targetId:pair[1].id,maxShift});if(r)setResult(r.result);}}>共通音声を解析</Button></div>{result&&<div role="status"><p>移動候補：{result.offset.toFixed(3)} 秒 ／ 一致度 {Math.round(result.score*100)}% {result.reliable?'':'· 一致が不確かなため自動適用できません'}</p><Button disabled={busy||!result.reliable||result.updatedAt!==state.updatedAt} onClick={()=>run('audio.syncApply',{targetId:result.targetId,start:result.start,projectId:result.projectId,updatedAt:result.updatedAt})}>同期候補を適用</Button><small>{result.note}</small></div>}<div className="pro-form-row"><Num label="音声クロスフェード（秒）" value={fade} set={setFade} min={1/state.fps} max={10}/><Button disabled={busy||pair.some(c=>c.track!=='audio')} onClick={()=>{const sorted=[...pair].sort((a,b)=>a.start-b.start);run('audio.crossfade',{leftId:sorted[0].id,rightId:sorted[1].id,duration:fade});}}>等電力でクロスフェード</Button></div><small>フェードはカット点の前後の未使用音声を使います。素材が足りない場合は適用できません。</small></>:<p>Ctrl＋クリックで2つのクリップを選択してください。</p>}</div></details>
 <details name="pro-timeline"><summary>モーションの一括調整</summary><div className="pro-tool-body"><p>{graphics.length} グラフィックを選択中</p><div className="pro-form-row"><Num label="表示時間（秒）" value={motionDuration} set={setMotionDuration} min={.1}/><Num label="入退場を保護する秒数" value={protect} set={setProtect} max={10}/><Button disabled={busy||!graphics.length} onClick={()=>run('graphics.batch',{ids:graphics,action:'duration',duration:motionDuration,protect})}>入退場を保って尺変更</Button><Num label="順次表示の時間差（秒）" value={gap} set={setGap} max={10}/><Button disabled={busy||!graphics.length} onClick={()=>run('graphics.batch',{ids:graphics,action:'stagger',gap})}>時間差をつける</Button></div><div className="button-row">{[['reverse','動きを逆再生'],['front','最前面へ'],['back','最背面へ']].map(([action,label])=><Button key={action} disabled={busy||!graphics.length} onClick={()=>run('graphics.batch',{ids:graphics,action})}>{label}</Button>)}</div></div></details></div>;
}
export function CompositionPanel({state,clock,run,busy}){
 const [preset,setPreset]=useState('chapter'),[title,setTitle]=useState('ここに見出し'),[subtitle,setSubtitle]=useState('伝えたいポイント'),[duration,setDuration]=useState(6),[color,setColor]=useState('#45d5ca');
 return <details className="finishing-panel"><summary>複数レイヤーのモーション構成</summary><Field label="構成"><select value={preset} onChange={e=>setPreset(e.target.value)}>{COMPOSITIONS.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></Field><Field label={preset==='steps'?'3項目（／で区切る）':'見出し'}><input value={title} maxLength={80} onChange={e=>setTitle(e.target.value)}/></Field><Field label="補足・右側の文字"><input value={subtitle} maxLength={120} onChange={e=>setSubtitle(e.target.value)}/></Field><div className="field-row"><Num label="長さ（秒）" value={duration} set={setDuration} min={2} max={60}/><Field label="アクセント"><input type="color" value={color} onChange={e=>setColor(e.target.value)}/></Field></div><Button className="primary full-width" disabled={busy||!title.trim()} onClick={()=>run('graphics.compose',{preset,title,subtitle,start:clock.time,duration,color})}>再生位置に構成を追加</Button><p className="muted-copy">文字・帯・線を独立したレイヤーとして配置します。追加後は画面上のドラッグやキーフレームで個別に調整できます。</p></details>;
}
