import React,{useEffect,useState} from 'react';
import {FolderOpen,Copy,Plus} from 'lucide-react';
import {request,timecode} from './model';
import {Button,Field} from './ui';
export default function ProjectBrowser({state,run,onOpen}){
  const [projects,setProjects]=useState([]),[error,setError]=useState('');
  useEffect(()=>{let live=true;request('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command:'project.list',args:{}})}).then(r=>{if(live)setProjects(r.result.projects);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[state.id,state.updatedAt]);
  return <section className="project-library"><h3>プロジェクト</h3>{error&&<p className="inline-error">{error}</p>}<div className="project-grid">{projects.map(project=><button key={project.id} className={'project-tile '+(project.id===state.id?'active':'')} data-action="project.switch" data-entity-id={project.id} onClick={async()=>{if(project.id===state.id)return;const r=await run('project.switch',{id:project.id});if(r)onOpen();}}><FolderOpen size={19}/><strong>{project.name}</strong><span>{project.width} × {project.height} · {project.fps} fps</span><small>{project.clips} クリップ · {timecode(project.duration)}</small></button>)}</div><Button icon={Copy} action="project.duplicate" onClick={async()=>{if(await run('project.duplicate'))onOpen();}}>現在のプロジェクトを複製</Button><form className="project-format" onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget);await run('project.settings',Object.fromEntries(['width','height','fps'].map(key=>[key,Number(form.get(key))])));}}><div className="field-row">{[['width','幅'],['height','高さ'],['fps','fps']].map(([key,label])=><Field label={label} key={key}><input name={key} type="number" defaultValue={state[key]} required min={key==='fps'?1:16} max={key==='fps'?120:8192} step={key==='fps'?1:2}/></Field>)}</div><button className="button" type="submit">シーケンス設定を保存</button></form></section>;
}
