import React,{useState} from 'react';
import {request} from './model';
const categories=[['プレゼン・タイトル','https://soundeffect-lab.info/sound/sub-category/business.html'],['演出・アニメ・切り替え','https://soundeffect-lab.info/sound/anime/'],['ボタン・システム','https://soundeffect-lab.info/sound/button/']];
export default function SoundLibrary({state,clock,run,busy,onUploaded}){
 const [category,setCategory]=useState(0),[query,setQuery]=useState(''),[id,setId]=useState(''),[level,setLevel]=useState(-18),[error,setError]=useState(''),[uploading,setUploading]=useState(false);
 const assets=state.assets.filter(a=>a.kind==='audio'),asset=assets.find(a=>a.id===id);
 const add=async()=>{if(!asset)return;let lane=Array.from({length:8},(_,i)=>i).find(l=>!state.clips.some(c=>c.track==='audio'&&(c.lane||0)===l&&c.start<clock.time+asset.duration&&c.start+c.duration>clock.time));if(lane===undefined){setError('空き音声トラックがありません。開始位置を変えてください。');return;}const response=await run('timeline.add',{assetId:id,track:'audio',lane,start:clock.time,in:0,duration:asset.duration,gain:10**(level/20)});if(response)setError('');};
 return <section className="sfx-library"><h3>効果音ラボから選ぶ</h3><label>用途<select value={category} onChange={e=>setCategory(Number(e.target.value))}>{categories.map(([name],i)=><option key={name} value={i}>{name}</option>)}</select></label><a className="button" href={categories[category][1]} target="_blank" rel="noreferrer">公式サイトで試聴・ダウンロード ↗</a><p className="muted-copy">選んだ音をダウンロードして、下のボタンから取り込めます。</p><label className="button">ダウンロードした効果音を取り込む<input type="file" accept="audio/*,.mp3,.wav,.m4a,.ogg,.flac" className="visually-hidden" disabled={uploading||busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setUploading(true);try{const data=new FormData();data.append('files',file);const response=await request('/api/upload',{method:'POST',body:data});onUploaded(response.state);setId(response.result[0]?.id||'');setError('');}catch(err){setError(err.message);}finally{setUploading(false);}}}/></label><label>取り込んだ音を検索<input placeholder="ファイル名" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="取り込んだ効果音を選択" value={id} onChange={e=>setId(e.target.value)}><option value="">音声を選択</option>{assets.filter(a=>a.name.toLowerCase().includes(query.toLowerCase())).map(a=><option key={a.id} value={a.id}>{a.name} · {a.duration.toFixed(2)}秒</option>)}</select>{asset&&<><audio key={asset.id} controls preload="none" src={asset.url}/><label>追加する音量（dB）<input type="number" min="-60" max="12" step=".1" value={level} onChange={e=>setLevel(Number(e.target.value))}/></label><button type="button" className="button primary" disabled={busy||!Number.isFinite(level)||level< -60||level>12} onClick={add}>再生ヘッド位置に配置</button></>}<a href="https://soundeffect-lab.info/agreement/" target="_blank" rel="noreferrer">効果音ラボの利用規約</a>{error&&<p role="alert">{error}</p>}</section>;
}
