import React,{useEffect,useRef,useState} from 'react';
import {Button,Field} from './ui';import {PROCESS_DEFAULTS,PROCESS_PRESETS} from '../server/audio-processing-options.mjs';
import {TEXT_MATERIALS} from '../server/text-materials.mjs';import {captionsSvg,captionDefaults} from '../server/caption-style.mjs';
export function AudioProcessingPanel({state,run,busy,ids,clock}){
 const [lane,setLane]=useState(0),[options,setOptions]=useState({...PROCESS_DEFAULTS}),[message,setMessage]=useState(''),[comparison,setComparison]=useState('processed'),player=useRef(null);
 const clips=state.clips.filter(c=>c.track==='audio'&&(ids?ids.includes(c.id):(c.lane||0)===lane)),first=clips[0],asset=state.assets.find(a=>a.id===first?.assetId),p=asset?.provenance,original=p?.kind==='cutton-audio-process'?state.assets.find(a=>a.id===p.sourceAssetId):null;
 useEffect(()=>{setOptions({...PROCESS_DEFAULTS,...(p?.options||{})});setMessage('');},[first?.id,asset?.id,state.id]);
 const set=(k,v)=>setOptions(o=>({...o,[k]:v}));
 const control=(key,label,min,max,step=1)=> <Field key={key} label={label}><div className="studio-value"><input aria-label={label} type="range" min={min} max={max} step={step} value={options[key]} onChange={e=>set(key,Number(e.target.value))}/><input aria-label={`${label} 数値`} type="number" min={min} max={max} step={step} value={options[key]} onChange={e=>set(key,Number(e.target.value))}/></div></Field>;
 const flag=(key,label)=><label className="checkbox-field"><input type="checkbox" checked={options[key]} onChange={e=>set(key,e.target.checked)}/>{label}</label>;
 const audition=comparison==='original'&&original?original:asset,start=comparison==='original'&&original?(p.sourceIn||0)+(first?.in||0):first?.in||0;
 return <details className="studio-audio"><summary>音声の仕上げ · ピッチ／ノイズ除去</summary><div className="studio-body">{!ids&&<Field label="対象トラック"><select value={lane} onChange={e=>setLane(Number(e.target.value))}>{Array.from({length:8},(_,n)=><option value={n} key={n}>A{n+1} · {state.clips.filter(c=>c.track==='audio'&&(c.lane||0)===n).length}クリップ</option>)}</select></Field>}<p className="muted-copy">{clips.length}個の音声クリップが対象。設定後「調整音を作って適用」で保存します。再調整は元音声から行います。</p><Field label="音声プリセット"><select value="" onChange={e=>{const p=PROCESS_PRESETS[e.target.value];if(p)setOptions({...PROCESS_DEFAULTS,...p.values});}}><option value="">プリセットを選択…</option>{Object.entries(PROCESS_PRESETS).map(([id,p])=><option key={id} value={id}>{p.name}</option>)}</select></Field>
 <details open><summary>音程と音量</summary>{control('pitch','ピッチ（半音）',-12,12,.1)}{flag('formant','声の特徴を保つ（フォルマント）')}{control('output','出力ゲイン（dB）',-24,12,.5)}</details>
 <details><summary>ノイズ・歯擦音</summary>{control('denoise','ノイズ低減（dB・0で無効）',0,30,1)}{control('noiseFloor','ノイズフロア（dB）',-80,-20,1)}{control('deess','サ行の抑制',0,1,.05)}{control('highpass','低音カット（Hz・0で無効）',0,1000,5)}{flag('gate','無音部分のノイズをゲートで抑える')}{control('gateDb','ゲートしきい値（dB）',-70,-10,1)}{control('gateRelease','ゲートリリース（ms）',20,1000,10)}</details>
 <details><summary>声の厚み・コンプレッサー</summary>{control('warmth','低域の厚み（dB）',-12,12,.5)}{control('presence','明瞭感（dB）',-12,12,.5)}{flag('compress','コンプレッサーを適用')}{control('threshold','しきい値（dB）',-50,0,.5)}{control('ratio','圧縮比',1,12,.5)}{control('makeup','補正ゲイン（dB）',0,12,.5)}</details>
 <details><summary>空間・ディレイ</summary>{control('room','ルームの短い反射音',0,.6,.01)}{control('delay','ディレイ量',0,.6,.01)}{control('delayMs','ディレイ間隔（ms）',20,1000,10)}<small>反射音の末尾はクリップの尺に収めます。</small></details>
 <Button className="primary full-width" disabled={!!busy||!clips.length} onClick={async()=>{clock?.pause();player.current?.pause();setMessage('音声を順番に処理しています…');const r=await run('audio.process',{ids:clips.map(c=>c.id),options});setMessage(r?`${r.result.count}個の調整音を保存しました。`:'処理できませんでした。エラー表示を確認してください。');}}>{busy==='audio.process'?'音声を処理中…':'調整音を作って適用'}</Button><small>24bit / 48kHzで保存。元のファイルは保持します。音声ミキサーのEQ・音量はさらに重ねて適用されます。</small>{message&&<p role="status">{message}</p>}
 {asset&&<details><summary>先頭の選択クリップを比較試聴</summary><div className="button-row"><Button disabled={!original} onClick={()=>{player.current?.pause();setComparison('original');}}>原音</Button><Button onClick={()=>{player.current?.pause();setComparison('processed');}}>保存済みの調整音</Button></div><small>{comparison==='original'&&original?'原音':'現在の素材'} · ミキサー／フェードを通す前の音</small><audio key={`${audition?.id}-${start}`} ref={player} controls preload="metadata" src={audition?.url} onPlay={e=>{clock?.pause();e.currentTarget.playbackRate=first?.speed||1;if(e.currentTarget.currentTime<start||e.currentTarget.currentTime>=start+first.duration*(first.speed||1))e.currentTarget.currentTime=start;}} onTimeUpdate={e=>{if(e.currentTarget.currentTime>=start+first.duration*(first.speed||1)){e.currentTarget.pause();e.currentTarget.currentTime=start;}}}/></details>}
 </div></details>;
}
export function BatchTools({state,items,clock,run,busy,onSelection}){
 const [rate,setRate]=useState(2),[ripple,setRipple]=useState(false);const audio=items.filter(i=>i.type==='clip'&&state.clips.some(c=>c.id===i.id&&c.track==='audio')).map(i=>i.id);
 return <div className="batch-tools"><details name="pro-timeline"><summary>一括編集 · {items.length}個</summary><div className="pro-tool-body"><p>Ctrl / ⌘＋クリックで複数選択。ドラッグでまとめて移動できます。</p><div className="field-row"><Field label="選択範囲の速度倍率"><select value={rate} onChange={e=>setRate(Number(e.target.value))}>{[.25,.5,.75,1.25,1.5,2,3,4].map(n=><option value={n} key={n}>{n}倍</option>)}</select></Field><label className="checkbox-field"><input type="checkbox" checked={ripple} onChange={e=>setRipple(e.target.checked)}/>後続の全トラックも詰める／広げる</label></div><p className="muted-copy">映像・音声は現在の速度に倍率を掛けます（最終0.25〜4倍）。選択した字幕・モーションも長さと間隔を合わせます。音声の音程は維持します。</p><div className="button-row"><Button disabled={!!busy||!items.length} onClick={()=>{clock.pause();run('timeline.batch',{items,action:'retime',rate,ripple});}}>速度を適用</Button><Button disabled={!!busy||!items.length} onClick={async()=>{const r=await run('timeline.batch',{items,action:'duplicate'});if(r)onSelection(r.result.items);}}>選択範囲の後ろに複製</Button><Button disabled={!!busy||!items.length} onClick={async()=>{const r=await run('timeline.batch',{items,action:'duplicate',at:clock.time});if(r)onSelection(r.result.items);}}>再生位置に複製</Button><Button disabled={!!busy||!items.length} onClick={()=>run('timeline.batch',{items,action:'remove'})}>選択を削除</Button></div>{!!audio.length&&<AudioProcessingPanel state={state} run={run} busy={busy} ids={audio} clock={clock}/>}</div></details><details name="pro-timeline"><summary>ショートカット</summary><div className="pro-tool-body shortcut-help"><p>タイムラインをクリックしてから操作できます。</p><dl>{[['Space','再生／停止'],['← / →','1フレーム移動（Shiftで10）'],['Alt＋← / →','選択要素を1フレーム移動（Shiftで10）'],['Ctrl / ⌘＋A','全要素を選択'],['Ctrl / ⌘＋D','選択範囲の後ろに複製'],['Delete','選択要素をまとめて削除'],['S / Shift＋S','選択クリップ／全トラックを分割'],['＋ / − / F','タイムライン拡大／縮小／全体表示'],['M','再生位置にマーカー'],['Ctrl / ⌘＋Z / Shift＋Z','元に戻す／やり直す']].map(([key,value])=><React.Fragment key={key}><dt><kbd>{key}</kbd></dt><dd>{value}</dd></React.Fragment>)}</dl></div></details></div>;
}
export function TextMaterialFields({draft,set}){
 const v={...captionDefaults,...draft},preview=captionsSvg({width:600,height:140,captions:[{...v,id:'material-preview',text:(v.text||'Cutton タイトル').slice(0,18),x:50,y:50,fontSize:42,start:0,duration:3,enterAnimation:'none',exitAnimation:'none',textAnimation:'none',karaoke:'none',words:[]}]},1);
 return <details className="text-materials" open><summary>文字の質感</summary><div className="material-preview" dangerouslySetInnerHTML={{__html:preview}}/><div className="material-presets">{TEXT_MATERIALS.map(p=><button type="button" key={p.id} onClick={()=>Object.entries(p.values).forEach(([k,v])=>set(k,v))}>{p.name}</button>)}</div><div className="effect-fields">{[['gloss','光沢',0,1,.05],['glow','光彩',0,24,1],['extrude','立体の厚み',0,12,1]].map(([k,label,min,max,step])=><Field label={label} key={k}><input type="number" min={min} max={max} step={step} value={v[k]} onChange={e=>set(k,Number(e.target.value))}/></Field>)}{[['glowColor','光彩の色'],['extrudeColor','立体の色'],['gradientMiddleColor','グラデーション中間色']].map(([k,label])=><Field key={k} label={label}><input type="color" value={v[k]} onChange={e=>set(k,e.target.value)}/></Field>)}</div><label className="checkbox-field"><input type="checkbox" checked={v.gradientMiddle} onChange={e=>set('gradientMiddle',e.target.checked)}/>3色グラデーション（下のグラデーション設定を有効に）</label><small>ここで質感を確認し、フォームの保存ボタンで動画に反映します。</small></details>;
}
