import React,{useState,useEffect} from 'react';
import {Button} from './ui';
export default function TimingTools({state,clock,items,run,busy,onSelectAll,onClear}){
 const [markIn,setIn]=useState(null),[markOut,setOut]=useState(null),[gap,setGap]=useState(0);
 useEffect(()=>{setIn(null);setOut(null);},[state.id]);
 useEffect(()=>{const key=e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,textarea,select,[contenteditable="true"]'))return;if(e.key.toLowerCase()==='i')setIn(clock.time);if(e.key.toLowerCase()==='o')setOut(clock.time);};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[clock]);
 const align=mode=>run('timeline.align',{items,mode,at:clock.time,gap});
 return <div className="timing-tools"><span>{items.length} 選択 · Ctrl＋クリックで複数選択</span><Button disabled={busy} onClick={onSelectAll}>全選択</Button><Button onClick={onClear}>解除</Button><select aria-label="選択要素のタイミングを揃える" value="" disabled={busy||!items.length} onChange={e=>align(e.target.value)}><option value="">タイミングを揃える…</option><option value="start">開始を揃える</option><option value="end">終了を揃える</option><option value="playhead">再生ヘッドに揃える</option><option value="sequence">順番に並べる</option></select><label>間隔<input aria-label="順番に並べる間隔（秒）" type="number" min="0" max="60" step=".05" value={gap} onChange={e=>setGap(Number(e.target.value))}/></label><Button disabled={busy} onClick={()=>run('timeline.splitAll',{at:clock.time})}>全トラック分割</Button><details><summary>範囲カット · I / O</summary><div className="button-row"><Button onClick={()=>setIn(clock.time)}>I 開始</Button><input aria-label="範囲カット開始（秒）" type="number" min="0" step=".001" value={markIn??''} onChange={e=>setIn(e.target.value===''?null:Number(e.target.value))}/><Button onClick={()=>setOut(clock.time)}>O 終了</Button><input aria-label="範囲カット終了（秒）" type="number" min="0" step=".001" value={markOut??''} onChange={e=>setOut(e.target.value===''?null:Number(e.target.value))}/><Button disabled={busy||markIn===null||markOut===null||markOut<=markIn} onClick={async()=>{const r=await run('timeline.cutRanges',{ranges:[{start:markIn,end:markOut}]});if(r){clock.seek(markIn);setIn(null);setOut(null);}}}>全トラックを範囲カット</Button></div><p>映像・音声を同じ範囲で切り、字幕・図形・マーカーも一緒に詰めます。元に戻す操作は1回です。</p></details></div>;
}
